version: '3.8'

services:
  web:
    build: ./create_satellite_xml
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./create_satellite_xml/:/usr/src/create_satellite_xml/
    ports:
      - 8000:8000
    env_file:
      - ./create_satellite_xml/.env.dev

  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
