# Generated by Django 4.0.4 on 2022-05-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Satxml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.IntegerField()),
                ('sat', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='My_Satellites',
        ),
    ]
