# Generated by Django 4.0.4 on 2022-05-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellit', '0002_my_satxml_delete_my_satellites'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Sat_xml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('satellites', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='My_Satxml',
        ),
    ]
